# Intended for swarm mode use, launch with: docker stack deploy -c compose.yaml -d your_stack_name
# Create docker secrets on the Docker host before deploying the stack

services:

  traefik:
    image: traefik:v3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - ./infra/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro   
      - ./infra/traefik/dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml:ro
      - ./infra/traefik/certs/cloudsec.crt:/var/traefik/certs/cloudsec.crt:ro
      - ./infra/traefik/certs/cloudsec.key:/var/traefik/certs/cloudsec.key:ro
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: secapp-backend:latest
    build: ./app/backend
    secrets:
      - aws_access_key
      - aws_secret_key
      - aws_region
      - s3_bucket
      - dynamo_table
    networks:
      - app-network
    deploy:
      replicas: 1

  frontend:
    image: secapp-frontend:latest
    build: ./app/frontend
    networks:
      - app-network
    depends_on:
      - backend
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"  
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.rule=Host(`dashboard.itssecapp.com`)"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=8080"
      
networks:
  app-network:

secrets:
  aws_access_key:
    external: true
  aws_secret_key:
    external: true
  aws_region:
    external: true
  s3_bucket:
    external: true
  dynamo_table:
    external: true