# Intended for swarm mode use, launch with: docker stack deploy -c compose.yaml -d your_stack_name
# Create docker secrets on the Docker host before deploying the stack

services:

  backend:
    image: secapp-backend:latest
    build: ./app/backend
    secrets:
      - aws_access_key
      - aws_secret_key
      - aws_region
      - s3_bucket
      - dynamo_table
    networks:
      - app-network
    deploy:
      replicas: 1

  frontend:
    image: secapp-frontend:latest
    build: ./app/frontend
    networks:
      - app-network
    ports:
      - 80:8080
    depends_on:
      - backend
    deploy:
      replicas: 1

networks:
  app-network:

secrets:
  aws_access_key:
    external: true
  aws_secret_key:
    external: true
  aws_region:
    external: true
  s3_bucket:
    external: true
  dynamo_table:
    external: true